import { asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { tasks } from "../../../db/schema";
const areas=["Licitații","Personal Brand Bogdan","ONG","After School","Visceral"], owners=["Roxana","Bogdan","Împreună"], statuses=["De făcut","În lucru","Așteptăm","Blocat","Finalizat"], priorities=["Urgentă","Ridicată","Medie","Scăzută"];
const clean=(v:unknown,n=500)=>typeof v==="string"?v.trim().slice(0,n):"";
const message=(e:unknown)=>{const m=e instanceof Error?e.message:"Eroare neașteptată";return m.includes("no such table")?"Baza de date nu este încă pregătită.":m};
export async function GET(){try{return Response.json({tasks:await getDb().select().from(tasks).orderBy(asc(tasks.status),asc(tasks.dueDate),asc(tasks.id))})}catch(e){return Response.json({error:message(e)},{status:500})}}
export async function POST(request:Request){try{const p=await request.json() as Record<string,unknown>;const area=clean(p.area,80),project=clean(p.project,120),title=clean(p.title,240),owner=clean(p.owner,30),status=clean(p.status,30)||"De făcut",priority=clean(p.priority,30)||"Medie";if(!areas.includes(area)||!project||!title||!owners.includes(owner)||!statuses.includes(status)||!priorities.includes(priority))return Response.json({error:"Completează câmpurile obligatorii."},{status:400});const now=new Date().toISOString();const [task]=await getDb().insert(tasks).values({area,project,title,owner,status,priority,dueDate:clean(p.dueDate,10)||null,nextStep:clean(p.nextStep),link:clean(p.link),notes:clean(p.notes,2000),createdAt:now,updatedAt:now}).returning();return Response.json({task},{status:201})}catch(e){return Response.json({error:message(e)},{status:500})}}
export async function PATCH(request:Request){try{const p=await request.json() as Record<string,unknown>,id=Number(p.id);if(!Number.isInteger(id))return Response.json({error:"Actualizare invalidă."},{status:400});const values:Record<string,string|null>={updatedAt:new Date().toISOString()};if(p.status!==undefined){const v=clean(p.status,30);if(!statuses.includes(v))return Response.json({error:"Status invalid."},{status:400});values.status=v}if(p.priority!==undefined){const v=clean(p.priority,30);if(!priorities.includes(v))return Response.json({error:"Prioritate invalidă."},{status:400});values.priority=v}if(p.owner!==undefined){const v=clean(p.owner,30);if(!owners.includes(v))return Response.json({error:"Responsabil invalid."},{status:400});values.owner=v}if(p.dueDate!==undefined)values.dueDate=clean(p.dueDate,10)||null;if(p.nextStep!==undefined)values.nextStep=clean(p.nextStep);if(p.title!==undefined){const v=clean(p.title,240);if(!v)return Response.json({error:"Titlul este obligatoriu."},{status:400});values.title=v}if(p.project!==undefined){const v=clean(p.project,120);if(!v)return Response.json({error:"Proiectul este obligatoriu."},{status:400});values.project=v}const [task]=await getDb().update(tasks).set(values).where(eq(tasks.id,id)).returning();return Response.json({task})}catch(e){return Response.json({error:message(e)},{status:500})}}
export async function DELETE(request:Request){try{const id=Number(new URL(request.url).searchParams.get("id"));if(!Number.isInteger(id))return Response.json({error:"Task invalid."},{status:400});await getDb().delete(tasks).where(eq(tasks.id,id));return Response.json({ok:true})}catch(e){return Response.json({error:message(e)},{status:500})}}
