"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,CalendarDays,CheckCircle2,CirclePlus,Clock3,ExternalLink,Filter,LayoutDashboard,ListTodo,Trash2,X} from "lucide-react";
type Task={id:number;area:string;project:string;title:string;owner:string;dueDate:string|null;status:string;priority:string;nextStep:string;link:string;notes:string};
const areas=["Licitații","Personal Brand Bogdan","ONG","After School","Visceral"],statuses=["De făcut","În lucru","Așteptăm","Blocat","Finalizat"],owners=["Roxana","Bogdan","Împreună"],priorities=["Urgentă","Ridicată","Medie","Scăzută"];
const initials:Record<string,string>={"Licitații":"LI","Personal Brand Bogdan":"PB","ONG":"ON","After School":"AS","Visceral":"VI"};
const blank={area:"Licitații",project:"",title:"",owner:"Roxana",dueDate:"",status:"De făcut",priority:"Medie",nextStep:"",link:"",notes:""};
const cls=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","-");
const shortDate=(v:string|null)=>v?new Intl.DateTimeFormat("ro-RO",{day:"2-digit",month:"short"}).format(new Date(v+"T12:00:00")):"Fără termen";
export default function Dashboard(){
 const[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modal,setModal]=useState(false),[ownerFilter,setOwnerFilter]=useState("Toți"),[areaFilter,setAreaFilter]=useState("Toate"),[view,setView]=useState("Active"),[form,setForm]=useState(blank);
 useEffect(()=>{fetch("/api/tasks").then(r=>r.json().then(d=>({ok:r.ok,d}))).then(({ok,d})=>ok?setTasks(d.tasks):setError(d.error)).catch(()=>setError("Nu am putut încărca taskurile.")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:Record<string,unknown>;annotations?:Record<string,boolean>;execute:(input:Record<string,unknown>)=>Promise<unknown>};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool)=>Promise<unknown>|unknown}}).modelContext;
  if(typeof context?.registerTool!=="function")return;
  const register=(tool:Tool)=>Promise.resolve(context.registerTool(tool)).catch(()=>undefined);
  register({name:"list_command_center_tasks",description:"Listează taskurile din Command Center. Folosește înainte de creare sau actualizare pentru a evita duplicatele.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const r=await fetch("/api/tasks"),d=await r.json();if(!r.ok)throw new Error(d.error);return {tasks:d.tasks}}});
  register({name:"create_command_center_task",description:"Creează un task în Command Center NUMAI după ce utilizatorul a văzut propunerea și a confirmat explicit. Pentru chat-urile din proiectul Licitații folosește aria Licitații.",inputSchema:{type:"object",properties:{area:{type:"string",enum:areas},project:{type:"string"},title:{type:"string"},owner:{type:"string",enum:owners},dueDate:{type:"string",description:"Data YYYY-MM-DD sau șir gol"},status:{type:"string",enum:statuses},priority:{type:"string",enum:priorities},nextStep:{type:"string"},link:{type:"string"}},required:["area","project","title","owner","status","priority"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const r=await fetch("/api/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)}),d=await r.json();if(!r.ok)throw new Error(d.error);setTasks(v=>[...v,d.task]);return {created:true,task:d.task}}});
  register({name:"update_command_center_task",description:"Actualizează un task existent NUMAI după confirmarea explicită a utilizatorului. Identifică mai întâi taskul cu list_command_center_tasks.",inputSchema:{type:"object",properties:{id:{type:"integer"},title:{type:"string"},project:{type:"string"},owner:{type:"string",enum:owners},dueDate:{type:"string"},status:{type:"string",enum:statuses},priority:{type:"string",enum:priorities},nextStep:{type:"string"}},required:["id"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const r=await fetch("/api/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(input)}),d=await r.json();if(!r.ok)throw new Error(d.error);setTasks(v=>v.map(t=>t.id===d.task.id?d.task:t));return {updated:true,task:d.task}}});
 },[]);
 const today=new Date();today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()+7);const active=tasks.filter(t=>t.status!=="Finalizat");
 const overdue=active.filter(t=>t.dueDate&&new Date(t.dueDate+"T12:00:00")<today).length,next7=active.filter(t=>t.dueDate&&new Date(t.dueDate+"T12:00:00")>=today&&new Date(t.dueDate+"T12:00:00")<=week).length,blocked=active.filter(t=>t.status==="Blocat").length,done=tasks.filter(t=>t.status==="Finalizat").length;
 const visible=useMemo(()=>tasks.filter(t=>(ownerFilter==="Toți"||t.owner===ownerFilter||t.owner==="Împreună")&&(areaFilter==="Toate"||t.area===areaFilter)&&(view==="Toate"||(view==="Active"?t.status!=="Finalizat":t.status==="Finalizat"))),[tasks,ownerFilter,areaFilter,view]);
 async function add(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setError(d.error||"Taskul nu a fost salvat.");setTasks(v=>[...v,d.task]);setForm(blank);setModal(false)}
 async function change(id:number,status:string){const r=await fetch("/api/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})}),d=await r.json();r.ok?setTasks(v=>v.map(t=>t.id===id?d.task:t)):setError(d.error)}
 async function remove(id:number){if(!confirm("Ștergem acest task?"))return;const r=await fetch("/api/tasks?id="+id,{method:"DELETE"});r.ok?setTasks(v=>v.filter(t=>t.id!==id)):setError("Taskul nu a putut fi șters.")}
 return <main className="shell"><aside className="sidebar"><div className="brand"><span>B+R</span><div><strong>Command Center</strong><small>Workspace comun</small></div></div><nav><button className="nav-active"><LayoutDashboard size={18}/>Dashboard</button><button onClick={()=>{setAreaFilter("Toate");setView("Active")}}><ListTodo size={18}/>Toate taskurile</button></nav><p className="nav-label">ARII</p><div className="area-nav">{areas.map(a=><button key={a} className={areaFilter===a?"selected":""} onClick={()=>setAreaFilter(a)}><span>{initials[a]}</span>{a}</button>)}</div><div className="sidebar-note"><strong>Regula noastră</strong><p>Dacă afectează un proiect, informația intră aici.</p></div></aside>
 <section className="content"><header><div><p className="eyebrow">COMMAND CENTER</p><h1>Bună, Bogdan și Roxana.</h1><p>Tot ce trebuie urmărit, într-un singur loc.</p></div><button className="primary" onClick={()=>setModal(true)}><CirclePlus size={19}/>Task nou</button></header>
 <div className="stats"><article><span className="stat-icon red"><AlertTriangle size={20}/></span><div><b>{overdue}</b><small>Restante</small></div></article><article><span className="stat-icon amber"><CalendarDays size={20}/></span><div><b>{next7}</b><small>Următoarele 7 zile</small></div></article><article><span className="stat-icon blue"><Clock3 size={20}/></span><div><b>{blocked}</b><small>Blocate</small></div></article><article><span className="stat-icon green"><CheckCircle2 size={20}/></span><div><b>{done}</b><small>Finalizate</small></div></article></div>
 <section className="workcard"><div className="workhead"><div><h2>Taskuri</h2><p>{visible.length} afișate · {active.length} active în total</p></div><div className="filters"><Filter size={16}/><select value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)}><option>Toți</option>{owners.map(o=><option key={o}>{o}</option>)}</select><select value={areaFilter} onChange={e=>setAreaFilter(e.target.value)}><option>Toate</option>{areas.map(a=><option key={a}>{a}</option>)}</select></div></div><div className="tabs">{["Active","Finalizate","Toate"].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v}</button>)}</div>{error&&<div className="error">{error}</div>}{loading?<div className="empty">Se încarcă…</div>:visible.length===0?<div className="empty"><ListTodo size={32}/><h3>Niciun task aici</h3><p>Adăugați primul task și începeți să lucrați din aceeași listă.</p><button className="primary" onClick={()=>setModal(true)}>Adaugă un task</button></div>:<div className="task-list">{visible.map(t=><article className="task" key={t.id}><div className={"priority "+cls(t.priority)}/><div className="area-mark">{initials[t.area]}</div><div className="task-main"><div className="task-title"><strong>{t.title}</strong>{t.link&&<a href={t.link} target="_blank" rel="noreferrer" aria-label="Deschide documentul"><ExternalLink size={15}/></a>}</div><p>{t.area} · {t.project}{t.nextStep?" · Următorul pas: "+t.nextStep:""}</p></div><span className={"owner "+cls(t.owner)}>{t.owner}</span><span className="due">{shortDate(t.dueDate)}</span><select className="status" value={t.status} onChange={e=>change(t.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="delete" onClick={()=>remove(t.id)} aria-label="Șterge taskul"><Trash2 size={16}/></button></article>)}</div>}</section></section>
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><section className="modal"><div className="modal-head"><div><p className="eyebrow">TASK NOU</p><h2>Ce trebuie făcut?</h2></div><button onClick={()=>setModal(false)} aria-label="Închide"><X/></button></div><form onSubmit={add}><label className="full">Task<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex: Finalizare buget Lot 1"/></label><label>Arie<select value={form.area} onChange={e=>setForm({...form,area:e.target.value})}>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Proiect<input required value={form.project} onChange={e=>setForm({...form,project:e.target.value})} placeholder="Ex: EC DEFIS"/></label><label>Responsabil<select value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}>{owners.map(o=><option key={o}>{o}</option>)}</select></label><label>Deadline<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Prioritate<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label className="full">Următorul pas<input value={form.nextStep} onChange={e=>setForm({...form,nextStep:e.target.value})} placeholder="Acțiunea concretă care urmează"/></label><label className="full">Link documente<input type="url" value={form.link} onChange={e=>setForm({...form,link:e.target.value})} placeholder="https://..."/></label><div className="form-actions full"><button type="button" onClick={()=>setModal(false)}>Renunță</button><button className="primary" type="submit">Salvează taskul</button></div></form></section></div>}</main>
}
