"use client";
import {useState} from 'react';
import type {DragEvent} from 'react';
import {GripVertical,MoveRight,X} from 'lucide-react';
export type NodeRef={kind:'space'|'page'|'task';id:string|number;label:string};
export type DropTarget={kind:'space'|'page'|'task';id:string|number|null;label:string};
export type Organization={spaces:{id:string;parent:string|null}[];pages:{id:string;area:string;title:string;parent:string|null}[];taskOrder:number[]};
export type DragHandlers={start:(e:DragEvent,node:NodeRef)=>void;end:()=>void;over:(e:DragEvent,target:DropTarget)=>void;drop:(e:DragEvent,target:DropTarget)=>void;hint:string;targetKey:string;busy:boolean;moveDialog:(node:NodeRef)=>void};
export function branchIds(nodes:{id:string|number;parent:string|number|null}[],id:string|number){const ids=new Set([id]);let added=true;while(added){added=false;for(const n of nodes)if(n.parent!==null&&ids.has(n.parent)&&!ids.has(n.id)){ids.add(n.id);added=true}}return ids}
const targetKey=(target:DropTarget)=>target.kind+':'+target.id;
export function MoveHandle({node,drag}:{node:NodeRef;drag:DragHandlers}){return <button className="move-handle" type="button" draggable={!drag.busy} onDragStart={e=>{e.stopPropagation();drag.start(e,node)}} onDragEnd={drag.end} onClick={e=>{e.stopPropagation();drag.moveDialog(node)}} title="Trage pentru organizare sau apasă pentru mutare" aria-label={'Organizează '+node.label}><GripVertical size={15}/></button>}
export function OrganizationNavigation({layout,space,page,navigate,drag,addPage}:{layout:Organization;space:string;page:string;navigate:(area:string,page?:string)=>void;drag:DragHandlers;addPage:()=>void}){
 function pageTree(area:string,parent:string|null,depth=0):React.ReactNode{return layout.pages.filter(p=>p.area===area&&p.parent===parent).map(p=>{const target:DropTarget={kind:'page',id:p.id,label:p.title},node:NodeRef={kind:'page',id:p.id,label:p.title};return <div key={p.id} className={'organization-item page-item '+(drag.targetKey===targetKey(target)?'drop-highlight':'')} style={{paddingLeft:depth*12}} onDragOver={e=>{e.stopPropagation();drag.over(e,target)}} onDrop={e=>{e.stopPropagation();drag.drop(e,target)}}><div className="organization-row"><MoveHandle node={node} drag={drag}/><button className={page===p.title?'selected':''} onClick={()=>navigate(area,p.title)}>{p.title}</button></div>{drag.targetKey===targetKey(target)&&<small className="drop-caption">{drag.hint}</small>}{pageTree(area,p.id,depth+1)}</div>})}
 function spaceTree(parent:string|null,depth=0):React.ReactNode{return layout.spaces.filter(s=>s.parent===parent).map(s=>{const target:DropTarget={kind:'space',id:s.id,label:s.id},node:NodeRef={kind:'space',id:s.id,label:s.id};return <div key={s.id} className={'organization-item space-item '+(drag.targetKey===targetKey(target)?'drop-highlight':'')} style={{paddingLeft:depth*14}} onDragOver={e=>{e.stopPropagation();drag.over(e,target)}} onDrop={e=>{e.stopPropagation();drag.drop(e,target)}}><div className="organization-row"><MoveHandle node={node} drag={drag}/><button className={space===s.id?'selected':''} onClick={()=>navigate(s.id)}><span className="space-index">{String(layout.spaces.findIndex(n=>n.id===s.id)+1).padStart(2,'0')}</span>{s.id}</button></div>{drag.targetKey===targetKey(target)&&<small className="drop-caption">{drag.hint}</small>}{space===s.id&&<div className="nested-pages"><div className="pages-toolbar"><button className={!page?'selected':''} onClick={()=>navigate(s.id)}>Toate subiectele</button><button onClick={addPage} title="Pagină nouă">+</button></div>{pageTree(s.id,null)}</div>}{spaceTree(s.id,depth+1)}</div>})}
 const root:DropTarget={kind:'space',id:null,label:'Nivel principal'};
 return <div className="organization-tree"><p className="organization-help">Trage ⋮⋮ pentru organizare</p>{spaceTree(null)}<div className={'root-drop '+(drag.targetKey==='space:null'?'drop-highlight':'')} onDragOver={e=>drag.over(e,root)} onDrop={e=>drag.drop(e,root)}>Mută la nivel principal</div></div>
}
export function MoveDialog({node,layout,tasks,close,submit,busy,error}:{node:NodeRef;layout:Organization;tasks:{id:number;title:string}[];close:()=>void;submit:(target:DropTarget,position:string)=>void;busy:boolean;error?:string}){
 const options:DropTarget[]=[...(node.kind==='space'?[{kind:'space' as const,id:null,label:'Nivel principal'}]:[]),...layout.spaces.filter(s=>s.id!==node.id).map(s=>({kind:'space' as const,id:s.id,label:s.id})),...(node.kind!=='space'?layout.pages.filter(p=>p.id!==node.id).map(p=>({kind:'page' as const,id:p.id,label:p.area+' / '+p.title})):[]),...(node.kind==='task'?tasks.filter(t=>t.id!==node.id).map(t=>({kind:'task' as const,id:t.id,label:'Task: '+t.title})):[])];
 const [selected,setSelected]=useState('0'),[position,setPosition]=useState('inside');const target=options[Number(selected)];
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)close()}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="move-title"><div className="modal-head"><h2 id="move-title">Organizează: {node.label}</h2><button onClick={close} disabled={busy} aria-label="Închide"><X/></button></div><>{error&&<p className="error" role="alert">{error}</p>}</><form onSubmit={e=>{e.preventDefault();if(target)submit(target,position)}}><label className="full">Destinație<select value={selected} onChange={e=>{setSelected(e.target.value);setPosition('inside')}}>{options.map((o,i)=><option key={o.kind+':'+o.id} value={String(i)}>{o.label}</option>)}</select></label><label className="full">Poziție<select value={position} onChange={e=>setPosition(e.target.value)}><option value="inside">În interior / subcomponentă</option>{target?.kind===node.kind&&target.id!==null&&<><option value="before">Înainte</option><option value="after">După</option></>}</select></label><p className="full">Mutarea se salvează pentru întregul workspace. Taskurile își păstrează subtaskurile și documentele.</p><div className="form-actions full"><button type="button" disabled={busy} onClick={close}>Renunță</button><button className="primary" disabled={busy||!target} type="submit"><MoveRight size={16}/>{busy?'Se salvează…':'Mută'}</button></div></form></section></div>
}
