export type Field={key:string;label:string;type?:string;required?:boolean;options?:string[][];ref?:string};
const f=(key:string,label:string,type='text',required=false):Field=>({key,label,type,required});
const ref=(key:string,label:string,to:string,required=true):Field=>({key,label,ref:to,required});
const opts=(key:string,label:string,values:string[][]):Field=>({key,label,options:values});
const notes=f('notes','Note','textarea');
const tender=ref('tenderId','Licitație','tenders');
const category=opts('category','Categorie',[['administrative','Administrativ'],['technical','Tehnic'],['financial','Financiar'],['expert','Expert'],['eligibility','Eligibilitate'],['scoring','Punctaj'],['other','Altele']]);
category.required=true;
export const sections:Record<string,{label:string;hint:string;fields:Field[]}>= {
 companies:{label:'Companii',hint:'Datele companiilor participante.',fields:[f('name','Denumire','text',true),f('cui','CUI','text',true),f('registration','Nr. registrul comerțului'),f('address','Adresă'),f('representative','Reprezentant'),f('email','Email','email'),f('phone','Telefon','tel'),f('caen','Coduri CAEN'),f('cpv','Coduri CPV'),notes]},
 associations:{label:'Asocieri',hint:'Asocierile și liderii lor. Adaugă participanții în secțiunea Membri.',fields:[f('name','Denumire','text',true),ref('leaderId','Companie lider','companies'),notes]},
 members:{label:'Membri',hint:'Companiile participante și responsabilitățile în asociere.',fields:[ref('associationId','Asociere','associations'),ref('companyId','Companie','companies'),f('role','Rol','text',true),f('responsibility','Responsabilități','textarea'),f('share','Cotă de participare (%)','number')]},
 experience:{label:'Experiență similară',hint:'Contracte, beneficiari și dovezi pentru fiecare companie.',fields:[ref('companyId','Companie','companies'),f('title','Titlu contract','text',true),f('beneficiary','Beneficiar','text',true),f('description','Descriere','textarea'),f('value','Valoare','number'),opts('currency','Monedă',[['RON','RON'],['EUR','EUR'],['USD','USD']]),f('startDate','Data început','date'),f('endDate','Data sfârșit','date'),f('evidenceUrl','Link dovadă','url'),notes]},
 experts:{label:'Experți',hint:'Experții disponibili și competențele lor.',fields:[f('name','Nume','text',true),f('email','Email','email'),f('phone','Telefon','tel'),f('skills','Competențe','textarea'),f('certifications','Certificări','textarea'),opts('availability','Disponibilitate',[['unknown','Neconfirmată'],['available','Disponibil'],['unavailable','Indisponibil']]),notes]},
 requirements:{label:'Cerințe',hint:'Cerințele din documentație și acțiunile de pregătit.',fields:[tender,f('title','Cerință','text',true),category,f('sourceUrl','Link documentație','url'),f('sourceExcerpt','Extras din documentație','textarea'),opts('status','Stare',[['de verificat','De verificat'],['în lucru','În lucru'],['confirmat','Confirmat'],['lipsă','Lipsă']]),notes]},
 applications:{label:'Candidaturi',hint:'Leagă experții de licitații, completează formularele și selectează echipa.',fields:[tender,ref('expertId','Expert','experts'),f('role','Rol propus','text',true),ref('configurationId','Formular de evaluare','configurations',false),opts('status','Stare',[['ciornă','Ciornă'],['în lucru','În lucru'],['finalizat','Finalizat']]),f('selected','Selectat în echipă','checkbox'),notes]},
 documents:{label:'Documente',hint:'Evidența documentelor prin link, termene de valabilitate și verificarea semnăturii.',fields:[f('title','Titlu document','text',true),category,{...tender,required:false},ref('companyId','Companie','companies',false),ref('expertId','Expert','experts',false),f('url','Link document','url'),f('expiryDate','Valabil până la','date'),opts('signatureStatus','Semnătură',[['unknown','De verificat'],['unsigned','Nesemnat'],['signed','Semnat — verificat manual']]),opts('status','Stare',[['de obținut','De obținut'],['de verificat','De verificat'],['verificat','Verificat']]),notes]},
 dossiers:{label:'Dosare',hint:'Urmărește pregătirea dosarului pentru fiecare licitație.',fields:[tender,f('title','Titlu dosar','text',true),opts('status','Stare',[['în pregătire','În pregătire'],['de verificat','De verificat'],['pregătit','Pregătit']]),notes]},
 configurations:{label:'Formulare și punctaj',hint:'Configurează formularul experților și regulile preluate din documentație.',fields:[tender,f('title','Nume formular','text',true),notes]},
};
