'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {sections,Field} from './fields';
import ConfigEditor from './config-editor';
import './module.css';
type Row=Record<string,any>;
async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json();if(!r.ok)throw Error(d.error||'Operațiunea nu a reușit.');return d;}
async function all(kind:string){let items:Row[]=[],offset:number|null=0;while(offset!==null){const d=await api(`/api/licitatii/${kind}?limit=100&offset=${offset}`);items.push(...d.items);offset=d.nextOffset;}return items;}
const send=(method:string,data:Row)=>({method,headers:{'content-type':'application/json'},body:JSON.stringify(data)});
const emptyConfig=()=>({fields:[],criteria:[],factors:[],pricePoints:0,sourceExcerpt:''});
export default function Module({section}:{section:string}){
 const meta=sections[section];
 const [rows,setRows]=useState<Row[]>([]),[refs,setRefs]=useState<Record<string,Row[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tender,setTender]=useState(''),[owner,setOwner]=useState(''),[search,setSearch]=useState(''),[form,setForm]=useState<Row|null>(null),[saving,setSaving]=useState(false),[proposal,setProposal]=useState<Row|null>(null),[evaluation,setEvaluation]=useState<Row|null>(null),[prices,setPrices]=useState({offer:'',lowest:''});
 useEffect(()=>{const q=new URLSearchParams(location.search);setTender(q.get('tender')||'');},[]);
 useEffect(()=>{if(form||proposal||evaluation)document.querySelector<HTMLElement>('.lm-editor')?.scrollIntoView({behavior:'smooth',block:'start'});},[!!form,!!proposal,!!evaluation]);
 async function refresh(){const kinds=[...new Set(['companies','associations','experts','configurations',section])];const results=await Promise.all(kinds.map(all));const d=await api('/api/tenders');const next:Record<string,Row[]>={tenders:d.tenders};kinds.forEach((k,i)=>next[k]=results[i]);setRefs(next);setRows(next[section]);}
 useEffect(()=>{let active=true;setLoading(true);refresh().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return ()=>{active=false};},[section]);
 const linked=(kind:string,id:unknown)=>(refs[kind]||[]).find(r=>String(r.id)===String(id));
 const title=(row:Row)=>row.name||row.title||(section==='applications'?`${linked('experts',row.expertId)?.name||'Expert'} · ${row.role}`:section==='members'?`${linked('companies',row.companyId)?.name||'Companie'} · ${row.role}`:row.id);
 const visible=rows.filter(r=>(!tender||!meta.fields.some(f=>f.key==='tenderId')||String(r.tenderId)===tender)&&(!owner||!r.tenderId||[owner,'Împreună'].includes(linked('tenders',r.tenderId)?.owner))&&(title(r)+' '+JSON.stringify(r)).toLocaleLowerCase('ro').includes(search.toLocaleLowerCase('ro')));
 function edit(row?:Row){setError('');setNotice('');setForm(row?structuredClone(row):{...(meta.fields.some(f=>f.key==='tenderId')&&tender?{tenderId:Number(tender)}:{}),...(section==='configurations'?{config:emptyConfig()}:{}),...(section==='applications'?{answers:{},contracts:[],selected:false}: {})});}
 async function save(e:React.FormEvent){e.preventDefault();if(!form||saving)return;setSaving(true);setError('');try{const data:Row={};for(const field of meta.fields){const v=form[field.key];if(v!==undefined&&v!=='')data[field.key]=v;else if(form.id&&!field.required)data[field.key]=null;}
 if(section==='configurations')data.config=form.config;
 if(section==='applications'){data.answers=form.answers||{};data.contracts=(form.contracts||[]).map((c:Row)=>{const next={...c};if(!next.evidenceUrl)delete next.evidenceUrl;return next});if(!form.configurationId&&form.id)data.configurationId='';}
 const result=await api(`/api/licitatii/${section}`,send(form.id?'PATCH':'POST',{...data,...(form.id?{id:form.id,version:form.version}:{})}));setRows(v=>form.id?v.map(r=>r.id===result.item.id?result.item:r):[result.item,...v]);setForm(null);setNotice('Modificările au fost salvate.');refresh().catch(()=>setNotice('Salvat. Reîncarcă pagina pentru a actualiza listele asociate.'));}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 function fieldView(f:Field){let options=f.options;if(f.ref)options=(refs[f.ref]||[]).filter(r=>f.ref!=='configurations'||r.tenderId===Number(form?.tenderId)).map(r=>[String(r.id),r.name||r.title]);const value=form?.[f.key]??'';return <label key={f.key}>{f.label}{f.required?' *':''}{f.type==='checkbox'?<input type="checkbox" checked={value===true} onChange={e=>setForm({...form,[f.key]:e.target.checked})}/>:options?<select required={f.required} value={value} onChange={e=>{const v=e.target.value;setForm({...form,[f.key]:f.key==='tenderId'&&v?Number(v):v,...(f.key==='tenderId'?{configurationId:'',answers:{}}:{}),...(f.key==='configurationId'?{answers:{}}:{})})}}><option value="">Alege…</option>{options.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>:f.type==='textarea'?<textarea value={value} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input type={f.type||'text'} required={f.required} value={value} min={f.type==='number'?0:undefined} max={f.key==='share'?100:undefined} step="any" onChange={e=>setForm({...form,[f.key]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})}/>}</label>}
 async function propose(e:React.FormEvent){e.preventDefault();if(!proposal)return;setSaving(true);setError('');try{const d=await api(`/api/licitatii/${section}`,send('POST',{action:'propose-task',id:proposal.record.id,task:{title:proposal.title,owner:proposal.owner,dueDate:proposal.dueDate}}));location.assign('/confirm-change?id='+encodeURIComponent(d.proposal_id));}catch(e){setError((e as Error).message);setSaving(false)}}
 async function calculate(row:Row){setSaving(true);setError('');try{const result=await api('/api/licitatii/configurations',send('POST',{action:'evaluate',id:row.id,prices:prices.offer||prices.lowest?{offer:Number(prices.offer),lowest:Number(prices.lowest)}:{}}));setEvaluation({record:row,result});}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 const config=form?.configurationId?linked('configurations',form.configurationId)?.config:null;
 return <main className="lm"><header className="lm-bar"><Link href="/">← Command Center</Link><strong>Licitații</strong><Link href={'/licitatii?tender='+encodeURIComponent(tender)}>Plan de lucru și termene</Link></header><div className="lm-body"><nav aria-label="Secțiuni Licitații">{Object.entries(sections).map(([id,m])=><Link key={id} aria-current={section===id?'page':undefined} href={`/licitatii/${id}${tender?'?tender='+tender:''}`}>{m.label}</Link>)}</nav><section className="lm-content"><header><div><p>COMMAND CENTER / LICITAȚII</p><h1>{meta.label}</h1><p>{meta.hint}</p></div><button className="primary" onClick={()=>edit()}>+ Adaugă</button></header><div className="lm-filters"><label>Caută<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nume, titlu sau detalii"/></label>{meta.fields.some(f=>f.key==='tenderId')&&<><label>Licitație<select value={tender} onChange={e=>setTender(e.target.value)}><option value="">Toate licitațiile</option>{(refs.tenders||[]).map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Responsabil licitație<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Toți</option>{['Roxana','Bogdan','Împreună'].map(o=><option key={o}>{o}</option>)}</select></label></>}</div>{error&&<p role="alert" className="lm-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading?<p role="status">Se încarcă…</p>:<><p>{visible.length} înregistrări</p>{!visible.length?<div className="lm-empty"><h2>Nicio înregistrare în această selecție</h2><p>Adaugă prima înregistrare sau schimbă filtrele.</p></div>:<div className="lm-records">{visible.map(row=><article key={row.id}><div><h2>{title(row)}</h2><p>{row.tenderId?linked('tenders',row.tenderId)?.title:row.cui||row.beneficiary||row.email||linked('associations',row.associationId)?.name||linked('companies',row.leaderId||row.companyId)?.name}</p>{row.status&&<span className="lm-badge">{row.status}</span>}{row.selected&&<span className="lm-badge">Selectat în echipă</span>}{row.expiryDate&&<p>Valabil până la: {row.expiryDate}</p>}{row.notes&&<p>{row.notes}</p>}{(row.url||row.evidenceUrl||row.sourceUrl)&&<a target="_blank" rel="noreferrer" href={row.url||row.evidenceUrl||row.sourceUrl}>Deschide documentul ↗</a>}</div><div className="lm-actions"><button onClick={()=>edit(row)}>Editează</button>{row.tenderId&&<button onClick={()=>{setError('');setProposal({record:row,title:'Verifică: '+title(row),owner:linked('tenders',row.tenderId)?.owner||'Roxana',dueDate:''})}}>Propune task</button>}{section==='configurations'&&<button onClick={()=>{setPrices({offer:'',lowest:''});setEvaluation({record:row});}}>Evaluează echipa</button>}</div></article>)}</div>}</>}
 {form&&<section className="lm-editor" aria-labelledby="form-title"><h2 id="form-title">{form.id?'Editează':'Adaugă'} · {meta.label}</h2><form onSubmit={save}><div className="lm-grid">{meta.fields.map(fieldView)}</div>{section==='documents'&&<p>Leagă documentul de cel puțin o licitație, o companie sau un expert. Fișierele se adaugă prin link.</p>}{section==='configurations'&&<ConfigEditor value={form.config} onChange={config=>setForm({...form,config})}/>}{section==='applications'&&config&&<fieldset><legend>Răspunsurile expertului</legend><div className="lm-grid">{config.fields.map((f:Row)=><label key={f.id}>{f.label}{f.required?' *':''}{f.type==='checkbox'?<select value={form.answers?.[f.id]===true?'yes':form.answers?.[f.id]===false?'no':''} onChange={e=>setForm({...form,answers:{...form.answers,[f.id]:e.target.value===''?null:e.target.value==='yes'}})}><option value="">Necompletat</option><option value="yes">Da</option><option value="no">Nu</option></select>:f.type==='select'?<select value={form.answers?.[f.id]??''} onChange={e=>setForm({...form,answers:{...form.answers,[f.id]:e.target.value}})}><option value="">Alege…</option>{f.options.map((o:Row)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={f.type==='textarea'?'text':f.type} min={f.min} max={f.max} value={form.answers?.[f.id]??''} onChange={e=>setForm({...form,answers:{...form.answers,[f.id]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value}})}/>}</label>)}</div><h3>Contracte justificative</h3>{(form.contracts||[]).map((c:Row,i:number)=><div className="lm-rule" key={i}>{['organization','hours','topics','evidenceUrl'].map((k,j)=><label key={k}>{['Beneficiar','Ore','Număr teme','Link dovadă'][j]}<input type={j===1||j===2?'number':j===3?'url':'text'} min="0" value={c[k]??''} onChange={e=>{const contracts=[...form.contracts];contracts[i]={...c,[k]:j===1||j===2?Number(e.target.value):e.target.value};setForm({...form,contracts})}}/></label>)}<label>Contract complex<input type="checkbox" checked={c.complex} onChange={e=>{const contracts=[...form.contracts];contracts[i]={...c,complex:e.target.checked};setForm({...form,contracts})}}/></label><button type="button" onClick={()=>setForm({...form,contracts:form.contracts.filter((_:Row,n:number)=>n!==i)})}>Elimină contract</button></div>)}<button type="button" onClick={()=>setForm({...form,contracts:[...form.contracts||[],{organization:'',hours:0,topics:0,complex:false}]})}>+ Contract</button></fieldset>}{error&&<p role="alert" className="lm-error">{error}</p>}<div className="lm-actions"><button type="button" disabled={saving} onClick={()=>setForm(null)}>Renunță</button><button className="primary" disabled={saving} type="submit">{saving?'Se salvează…':'Salvează'}</button></div></form></section>}
 {proposal&&<section className="lm-editor"><h2>Propune un task</h2><p>Vei verifica și confirma propunerea înainte de crearea taskului.</p><form onSubmit={propose}><div className="lm-grid"><label>Titlu task<input required value={proposal.title} onChange={e=>setProposal({...proposal,title:e.target.value})}/></label><label>Responsabil<select value={proposal.owner} onChange={e=>setProposal({...proposal,owner:e.target.value})}>{['Roxana','Bogdan','Împreună'].map(o=><option key={o}>{o}</option>)}</select></label><label>Termen<input type="date" value={proposal.dueDate} onChange={e=>setProposal({...proposal,dueDate:e.target.value})}/></label></div><div className="lm-actions"><button type="button" onClick={()=>setProposal(null)}>Renunță</button><button disabled={saving} className="primary">Verifică propunerea</button></div></form></section>}
 {evaluation&&<section className="lm-editor"><h2>Evaluare · {evaluation.record.title}</h2><p>Se calculează candidaturile legate de acest formular și selectate în echipă.</p><div className="lm-grid"><label>Preț ofertă<input type="number" min="0.01" step="any" value={prices.offer} onChange={e=>setPrices({...prices,offer:e.target.value})}/></label><label>Cel mai mic preț<input type="number" min="0.01" step="any" value={prices.lowest} onChange={e=>setPrices({...prices,lowest:e.target.value})}/></label></div><div className="lm-actions"><button onClick={()=>setEvaluation(null)}>Închide</button><button className="primary" disabled={saving} onClick={()=>calculate(evaluation.record)}>Calculează</button></div>{evaluation.result&&<div aria-live="polite"><h3>Punctaj total: {evaluation.result.total??'Incomplet'}</h3><p>Tehnic: {evaluation.result.technical??'Neconfirmat'} · Preț: {evaluation.result.price??'Neconfirmat'}</p>{evaluation.result.breakdown.map((b:Row)=><p key={b.id}>{b.label}: {b.points??'Neconfirmat'} / {b.maxPoints}</p>)}{evaluation.result.people.map((p:Row)=><p key={p.id}>Candidatură {p.id.slice(0,8)}: {{pass:'Criterii îndeplinite — de verificat',fail:'Criterii neîndeplinite',unknown:'Date neconfirmate'}[p.eligibility as string]}{p.formIssues.length?' · '+p.formIssues.join('; '):''}</p>)}<p>{evaluation.result.notice}</p></div>}</section>}
 </section></div></main>
}
