export const masterContext = [
 {area:'Brand, Website & SEO',status:'Website activ; dezvoltări recente raportate pentru paginile de workshopuri și B2B.',nextStep:'Verifică paginile în producție și efectuează auditul SEO și de conversie.',rules:'Folosește catalogul și conținutul aprobat. Verifică implementările existente înainte de modificări. Identitate baby blue, ivory, Manrope și DM Serif Display.'},
 {area:'Training & Workshops',status:'Catalog existent; oferta se construiește din produsele și experiența documentată.',nextStep:'Structurează fiecare program după public, rezultate, module, metode, evaluare, dovezi și costuri.',rules:'BT_CATALOG_2025.pptx este sursa primară. Nu inventa ediții programate, participanți, testimoniale sau acreditări.'},
 {area:'Executive Coaching',status:'Servicii de coaching discutate; platforma de coaching este o idee inițiată.',nextStep:'Definește MVP-ul platformei de coaching.',rules:'Separă serviciile livrabile de funcțiile propuse ale aplicației. Verifică formularea și valabilitatea acreditărilor PCC/ICF și CPC/ICA înainte de publicare.'},
 {area:'Leadership in AI',status:'Concept de program structurat: 6 zile / 36 ore, 4 module; repere de lucru, nu ofertă finală.',nextStep:'Validează oferta Leadership in the New AI Landscape și dovezile care o susțin.',rules:'500 EUR / 2 zile este reper comercial discutat. Certificările și CPD trebuie verificate înainte de utilizare comercială.'},
 {area:'Board Games & Simulations',status:'Colliers / Bucharest 2035: concept comercial avansat, prezentare și specificații preliminare.',nextStep:'Validează conceptul cu clientul, prototipul și costurile pentru 6 seturi.',rules:'Nu trata jocul ca fabricat, testat sau validat. Aproximativ 100 de participanți este parametrul de lucru din brief. Păstrează distincte designul, pilotul, facilitarea și transferul.'},
 {area:'Learning Technology',status:'Platformă game design: arhitectură conceptuală; portofoliu de concepte digitale.',nextStep:'Prioritizează produsele și definește MVP-ul Client Discovery & Assessment.',rules:'Modelul organizațional persistent, generatorul de mecanici, motorul de stare și marketplace-ul sunt direcții propuse. Ipoteza de diferențiere nu este validare comercială.'},
 {area:'Tenders & Procurement Ro',status:'Flux comercial de tender services definit; documentația POLIAC–ASE este un studiu de caz intern.',nextStep:'Standardizează metodologia de verificare a cerințelor, dovezilor, contradicțiilor și blocajelor.',rules:'Extrage cerințele din documentele oficiale. Nu confunda Tech and Play cu Poliac. Nu transforma documentele confidențiale ale consorțiului în materiale publice.'},
 {area:'Sales, Partnerships & Pitches',status:'Există mai multe versiuni PPTX/PDF ale pitchului și materiale comerciale.',nextStep:'Identifică ultima versiune aprobată a pitchului și clarifică modelul comercial al parteneriatelor.',rules:'Nu deduce aprobarea din numele sau data fișierului. Precizează cine vinde, contractează, livrează, deține materialele și cum se împart veniturile.'},
 {area:'YoungMinds & Education',status:'Planificare și cercetare pentru locație, afterschool și model educațional; assessment adaptiv în stadiu conceptual.',nextStep:'Validează locația și modelul operațional YoungMinds.',rules:'Separă YoungMinds, TECH AND PLAY ILECA SRL și brandul Bogdan. Estimările de investiții, numărul copiilor și bugetul prototipului sunt orientative și necesită validare.'},
 {area:'Research & Product Validation',status:'Direcții de cercetare aplicată: simulări, leadership și AI, coaching adaptiv, learning analytics, instructional design.',nextStep:'Construiește dovezile pentru eficiența simulărilor și transferul învățării în comportamente.',rules:'Separă cercetarea științifică, ipotezele de produs și afirmațiile comerciale validate. Nu reutiliza cifre agregate despre experiență fără reconciliere cu documentele-sursă.'},
];
